services:
  pypi:
    container_name: pypi
    image: pypiserver/pypiserver:v2.4.0
    restart: always
    ports:
      - 8081:8080
    volumes:
      - "D:/resource/volume/pypi:/data/packages"
    command: "run -P . -a . -o"
