services:
  miniserver:
    container_name: miniserver
    image: svenstaro/miniserve:0.32.0
    restart: no
    ports:
      - 8080:8080
    volumes:
      - "D:/resource/volume/share:/share"
    command: "-u -U -o -q /share"
