services:
  ftp:
    container_name: ftp
    image: fauria/vsftpd
    restart: no
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - "D:/resource/volume/share:/home/vsftpd/ftp"
    environment:
      - FTP_USER=ftp
      - FTP_PASS=123456
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS=192.168.31.133
