"$schema" = 'https://starship.rs/config-schema.json'

format = """
\u256D[\ue0b6](c0)$os$shell$hostname$username[\ue0b0](fg:c0 bg:c1)\
$directory[\ue0b0](fg:c1 bg:c2)\
$time[\ue0b0](fg:c2 bg:c3)\
$cmd_duration[\ue0b0](c3)\
(
\u251C\u2500\
$git_branch$git_status\
$conda$python\
)
\u2570\u2500$character"""
palette = 'fern'

[palettes.fern]
c0 = '#51D2EC'
c1 = '#769ff0'
c2 = '#aba0ed'
c3 = '#D2C5F7'
font_dark = '#2d3436'
font_light = '#e3e5e5'

# line1-------------------------------------------------------------------------
[os]
disabled = false
format = "[$symbol](fg:font_dark bg:c0)"

[os.symbols]
Linux = "\uf17c "
Macos = "\ue711 "
Windows = "\uf17a "

Amazon = "\uf270 "
Android = "\ue70e "
Arch = "\uf303 "
CentOS = "\uef3d "
Debian = "\ue77d "
Fedora = "\uef46 "
FreeBSD = "\uf28f "
Mint = "\uF30e "
Redhat = "\uef5d "
Ubuntu = "\uf31c "

[shell]
bash_indicator = "\uebca"
cmd_indicator = "\uebc4"
disabled = false
fish_indicator = "\uee41"
format = "[$indicator ](fg:font_dark bg:c0)"
ion_indicator = "\ue66b"
powershell_indicator = "\uebc7"
unknown_indicator = "\uf489 ?"
zsh_indicator = "\uf489 zsh"

[hostname]
disabled = false
format = "[\ueba9 $hostname ](fg:font_dark bg:c0)"
ssh_only = true

[username]
disabled = false
format = "[\uf2c0 $user ](fg:font_dark bg:c0)"
show_always = true

[directory]
format = "[\uea83 $path ](fg:font_dark bg:c1)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
format = "[\uf43a $time](fg:font_dark bg:c2)"
style = "bg:#1d2230"
time_format = "%X"

[cmd_duration]
format = "[\uf252 $duration](fg:font_dark bg:c3)"
min_time = 1
show_milliseconds = true

# line2-------------------------------------------------------------------------
[git_branch]
format = '[$symbol $branch](#ff9e64)'
symbol = "\uf418"

[git_status]
format = "[( \uf044  $all_status)( $ahead_behind) ](#ff9e64)"

ahead = "\uf46a \u21E1${count}"
behind = "\uf46a \u21E3${count}"
diverged = "\uf46a \u21E1${ahead_count} \u21E3${behind_count}"
up_to_date = "\u2261"

conflicted = "!($count )"
deleted = "-($count )"
modified = '~($count )'
renamed = ">($count )"
staged = "+($count )"
stashed = '$($count )'
untracked = '?($count )'

[conda]
format = "[\uec16 $environment ](#9ece6a)"

[python]
format = "[(\ue235 $version) ](#E5C07B)"
