services:
  runner:
    image: glatzel/github-action-runner:2.325.0
    environment:
      - GH_OWNER=${GH_OWNER}
      - GH_REPOSITORY=${GH_REPOSITORY}
      - GH_TOKEN=${GH_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
